Repository 4GeeksAcademy/website-v2, pull requests merged in 2021-05, with the labels that each got.

#733 Update about_4geeks.us.yaml
  src/data/components/about_4geeks/about_4geeks.us.yaml
Labels: 🖐🏽 Awaiting Feedback

#731 Update choose_your_program.us.yaml
  src/data/components/choose_your_program/choose_your_program.us.yaml
Labels: 🖐🏽 Awaiting Feedback

#761 Feature - Outcomes page
  src/assets/css/style.css
  src/data/page/outcomes.es.yml
  src/data/page/outcomes.us.yml
  src/new_components/ChooseProgram/index.js
  src/new_components/Heading/index.js
  src/new_components/Sections/index.js
  src/templates/outcomes.js
Labels: New Website

#913 Solved: confusion with day and month for Spanish location users
  src/actions.js
  src/data/location/santiago-chile.us.yaml
  src/data/page/outcomes.es.yml
  src/data/page/outcomes.us.yml
  src/new_components/Marquee_v2/index.js
  src/new_components/UpcomingDates/index.js
  src/templates/calendar.js
  src/templates/outcomes.js
Labels: :star: P1, bug, enhancement
